### ISSUE TITLE
Final simplex tableau

### ISSUE THREAD

**Issue by ashwani0423** [coin-or/python-mip#171]
I need to download the final simplex tableau from the cbc for my research. Is it possible to do so?

**Comment by tkralphs** [comment]
There is no final tableau for problems solved with Cbc, as it is meant for solving integer programs using a branch-and-cut approach. If what you are really solving is an LP, then there would be a final tableau in principle, but since python-mip is using the Cbc C API, as far as I know, I doubt it has access to the tableau. [CyLP](https://github.com/Coin-or/CyLP) is another Python interface to Cbc/Clp that would give you access to the tableau after solving an LP, so you could take a look at that.
