### ISSUE TITLE
[QUESTION] Multiplication of two binary variables

### ISSUE THREAD

**Issue by rodo-hf** [coin-or/python-mip#73]
Hi, is it possible to make an objectivefunction (OF)/constraint with a multiplication of two decision variables? E.g., M1 and M2 are given constants and OF=M1x1*(1-x2) + M2x3*(1-x4), such that M1 is only added if decision variables x1=1 and x2=0 (and M2 if x3=1 and x4=0).

**Comment by tuliotoffolo** [comment]
Hello @rodo-hf! 
The current version of Python-MIP supports only **linear functions**. We plan to include support to quadratic functions in version 2.0. 

Have you tried to linearize your objective function? Assuming x1 and x2 are binary variables, you could replace x1*(1-x2) for a variable whose value is calculated by linear constraints. For example:

y12 <= x1
y12 <= (1-x2)
y12 >= x1 + (1-x2) - 1

will ensure that y12=1 when x1=1 and x2=0 and y12=0 otherwise. Of course this may introduce many new variables into your model... but I hope it is helpful.
